export type Course = {
  id: string;
  title: string;
  platform: "Coursera" | "Udemy" | "Microsoft Learn" | "edX";
  skillTags: string[];
  level: "Beginner" | "Intermediate" | "Advanced";
  priceModel: "free" | "paid_once" | "subscription" | "unknown";
  priceAmount: number | null;
  currency: string | null;
  priceInterval: "month" | "year" | null;
  priceText: string;
  durationText: string;
  rating?: number;
  language: string;
  certificate: boolean;
  shortDescription: string | null;
  syllabusBullets: string[];
  prerequisitesBullets: string[];
  externalUrl: string;
};
